FROM bde2020/spark-master:3.3.0-hadoop3.3

RUN apk add --no-cache \
    build-base \
    python3-dev \
    freetype-dev \
    libpng-dev \
    openblas-dev \
    jpeg-dev \
    zlib-dev

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    numpy==1.21.6 \
    pandas==1.3.5 \
    matplotlib==3.5.3 \
    textblob